<script setup lang="ts">
import {MOTION_PRESETS,PRODUCT_ENTRANCES,TEXT_ENTRANCES,CAMERA_MOVEMENTS,SCENE_TRANSITIONS,ATMOSPHERE_EFFECTS,SOUND_EFFECTS,PRODUCT_FINISHES,motionSettings,identifyMotionPreset,soundAsset,type VideoMotionSettings} from '~/shared/video-studio/effect-catalog'
import type {VideoDocument} from '~/shared/video-studio/model'
const doc=defineModel<VideoDocument>({required:true})
const m=computed(()=>motionSettings(doc.value.motion))
const selected=computed(()=>identifyMotionPreset(doc.value.motion,doc.value.transition))
const fields=[{key:'product',label:'Entrada dos produtos',items:PRODUCT_ENTRANCES},{key:'text',label:'Entrada dos textos',items:TEXT_ENTRANCES},{key:'price',label:'Entrada do preço',items:PRODUCT_ENTRANCES},{key:'camera',label:'Movimento da tela toda',items:CAMERA_MOVEMENTS},{key:'finish',label:'Acabamento dos produtos',items:PRODUCT_FINISHES}] as const
function apply(id:string){const p=MOTION_PRESETS.find(p=>p.id===id)!;doc.value={...doc.value,motion:{...p.motion,atmosphere:[...p.motion.atmosphere]},transition:p.transition,effects:[...new Set([...doc.value.effects,'zoom','shake'] as const)]}}
function set(key:keyof VideoMotionSettings,value:string){doc.value={...doc.value,motion:{...m.value,[key]:value}};if(key==='camera'&&value!=='none'&&!doc.value.effects.includes('shake'))doc.value.effects.push('shake')}
function atmosphere(id:VideoMotionSettings['atmosphere'][number]){const current=m.value.atmosphere;if(!current.includes(id)&&current.length>=8)return;doc.value={...doc.value,motion:{...m.value,atmosphere:current.includes(id)?current.filter(v=>v!==id):[...current,id]}}}
const value=(e:Event)=>(e.target as HTMLSelectElement).value
</script>

<template>
 <section class="motion-library" aria-label="Biblioteca de movimentos">
  <div class="motion-heading"><span>ESTILO DO MOVIMENTO</span><strong>Mais impacto, do seu jeito.</strong><p>Escolha uma combinação. Produtos, texto, preço e som se movimentam juntos.</p></div>
  <div class="motion-presets"><button v-for="p in MOTION_PRESETS" :key="p.id" type="button" :aria-pressed="selected===p.id" :class="{active:selected===p.id}" @click="apply(p.id)"><i :style="{'--accent':p.color}" aria-hidden="true">{{ p.id==='storm'?'ϟ':p.id==='party'?'✦':p.id==='neon'?'◈':p.id==='flash'?'»':p.id==='focus'?'◎':'↗' }}</i><strong>{{ p.name }}</strong><small>{{ p.description }}</small></button></div>
  <p class="motion-note" role="status">{{ selected?'Combinação aplicada. Dê o play na prévia para conferir.':'Você pode manter o movimento atual ou experimentar uma combinação.' }}</p>
  <details><summary>Ajustar cada movimento</summary><div class="motion-fields">
   <label v-for="field in fields" :key="field.key">{{ field.label }}<select :value="m[field.key]||'clean'" @change="set(field.key,value($event))"><option v-for="item in field.items" :key="item.id" :value="item.id">{{ item.name }}</option></select></label>
   <label>Transição entre ofertas<select v-model="doc.transition"><option v-for="t in SCENE_TRANSITIONS" :key="t.id" :value="t.id">{{ t.name }}</option></select></label>
   <label>Velocidade das entradas<select :value="m.speed" @change="set('speed',value($event))"><option value="fast">Rápida · varejo</option><option value="balanced">Mais moderada</option></select></label>
  </div><p class="motion-subtitle">Elementos adicionais no fundo · até 8 ao mesmo tempo</p><div class="motion-checks"><label v-for="effect in ATMOSPHERE_EFFECTS" :key="effect.id"><input type="checkbox" :checked="m.atmosphere.includes(effect.id)" :disabled="!m.atmosphere.includes(effect.id)&&m.atmosphere.length>=8" @change="atmosphere(effect.id)"/>{{ effect.name }}</label></div></details>
  <details><summary>Escolher e ouvir os sons</summary><p class="motion-note">Os sons acompanham a entrada e o destaque do preço. O volume fica em “Locução e som”.</p><div class="motion-fields"><label v-for="field in ([{key:'transitionSound',name:'Som da entrada'},{key:'accentSound',name:'Som do impacto'}] as const)" :key="field.key">{{ field.name }}<select :value="m[field.key]" @change="set(field.key,value($event))"><option v-for="sound in SOUND_EFFECTS" :key="sound.id" :value="sound.id">{{ sound.name }}</option></select><audio :key="m[field.key]" controls preload="none" :src="'/video-studio/audio/'+soundAsset(m[field.key])"/></label></div></details>
 </section>
</template>

<style scoped>
.motion-library{margin:24px 0;border:1px solid #d9e5dd;border-radius:18px;padding:22px;background:#fff}.motion-heading>span{font-size:10px;letter-spacing:1.5px;color:#377457;font-weight:700}.motion-heading>strong{display:block;font-size:22px;margin-top:8px}.motion-heading p,.motion-note{font-size:13px;line-height:1.5;color:#64746c;margin:8px 0 16px}.motion-presets{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px}.motion-presets button{border:1px solid #e0e7e2;border-radius:12px;background:#f8faf8;text-align:left;padding:12px;cursor:pointer;color:#20382a}.motion-presets button.active{border-color:#2a7955;box-shadow:0 0 0 1px #2a7955;background:#edf7ef}.motion-presets i{display:grid;place-items:center;font-size:30px;font-style:normal;background:radial-gradient(ellipse at 35% 35%,#355b43,#11271c);color:var(--accent);height:60px;border-radius:8px;margin-bottom:10px;text-shadow:0 0 15px var(--accent)}.motion-presets strong{display:block;font-size:13px}.motion-presets small{display:block;line-height:1.4;font-size:11px;color:#63786b;margin-top:5px}.motion-library details{border-top:1px solid #e3ebe6;padding:14px 0 0;margin-top:14px}.motion-library summary{cursor:pointer;font-weight:600;font-size:14px}.motion-fields{display:grid;grid-template-columns:1fr 1fr;gap:14px;margin-top:16px}.motion-fields label{display:flex;flex-direction:column;gap:7px;font-size:12px;font-weight:600}.motion-fields select{width:100%;border:1px solid #cfddd3;border-radius:8px;background:#fff;padding:10px 8px;font:inherit;color:#294934}.motion-fields audio{width:100%;height:34px}.motion-checks{display:grid;grid-template-columns:1fr 1fr;gap:10px;font-size:12px}.motion-checks label{display:flex;gap:7px;align-items:center}.motion-subtitle{font-size:12px;font-weight:700;margin:20px 0 12px}.motion-library input{accent-color:#26754f}@media(max-width:550px){.motion-library{padding:15px}.motion-presets{grid-template-columns:1fr 1fr}.motion-fields{grid-template-columns:1fr}}
</style>
