<script setup lang="ts">
import {VIDEO_BACKGROUNDS,backgroundAsset} from '~/shared/video-studio/backgrounds'
import {VIDEO_COLOR_PALETTES,VIDEO_TEXT_COLORS} from '~/shared/video-studio/personalization'
import {SCENE_TRANSITIONS,SOUND_EFFECTS,motionSettings,soundAsset,type VideoMotionSettings} from '~/shared/video-studio/effect-catalog'
import {newVideoFromTemplate} from '~/shared/video-studio/templates'
import {flyerRecipe} from '~/shared/video-studio/flyer-recipes'
import {VIDEO_EFFECTS,type VideoDocument} from '~/shared/video-studio/model'
const doc=defineModel<VideoDocument>({required:true})
const supportsCatalog=computed(()=>!!flyerRecipe(doc.value.theme)||(doc.value.theme==='impact'&&doc.value.layoutVersion===2))
const motion=computed(()=>motionSettings(doc.value.motion))
function setSound(key:'transitionSound'|'accentSound',event:Event){doc.value.motion={...motion.value,[key]:(event.target as HTMLSelectElement).value as VideoMotionSettings['transitionSound']}}
function restore(){const original=newVideoFromTemplate(doc.value.theme);doc.value={...doc.value,appearance:undefined,background:undefined,motion:original.motion,effects:original.effects,intensity:original.intensity,transition:original.transition,audio:{...doc.value.audio,music:original.audio.music,musicVolume:original.audio.musicVolume,effectsVolume:original.audio.effectsVolume,sounds:original.audio.sounds}}}
</script>
<template>
 <section class="personalize">
  <template>
   <h3>Fundo do vídeo</h3><p>Troque o cenário sem mudar os produtos, a logo ou os preços.</p>
   <div class="backgrounds"><button :class="{selected:!doc.background}" :aria-pressed="!doc.background" @click="doc.background=undefined"><span class="original">↺</span>Original do modelo</button><button v-for="bg in VIDEO_BACKGROUNDS" :key="bg.id" :class="{selected:doc.background===bg.id}" :aria-pressed="doc.background===bg.id" @click="doc.background=bg.id"><img :src="'/video-studio/templates/'+backgroundAsset(bg.id,'horizontal')" alt="" loading="lazy"/>{{ bg.name }}</button></div>
  </template>
  <h3>Cores dos textos</h3><p>Escolha uma combinação ou ajuste cada texto separadamente. A logo e as formas da etiqueta mantêm suas cores.</p><div class="palettes"><button v-for="palette in VIDEO_COLOR_PALETTES" :key="palette.id" :aria-pressed="doc.appearance?.textColor===palette.textColor" :class="{selected:doc.appearance?.textColor===palette.textColor}" @click="doc.appearance={textColor:palette.textColor,accent:palette.accent}"><i :style="{background:palette.textColor||'#fff',borderColor:palette.accent||'#aeb5c8'}"/>{{ palette.name }}</button></div><details open><summary>Cor de cada texto</summary><label v-for="field in VIDEO_TEXT_COLORS" :key="field.key">{{ field.label }}<span class="color-controls"><input type="color" :aria-label="field.label" :value="doc.appearance?.[field.key]||doc.appearance?.textColor||'#ffffff'" @input="doc.appearance={...doc.appearance,[field.key]:($event.target as HTMLInputElement).value}"/><button type="button" :aria-label="`Restaurar cor: ${field.label}`" @click="doc.appearance={...doc.appearance,[field.key]:undefined}">↺</button></span></label></details>
  <label class="campaign">Texto da campanha<input v-model="doc.campaign" maxlength="65"/><small>Ao mudar o título, o selo do modelo é substituído pelo seu texto na prévia.</small></label>
  <h3>Transição entre as ofertas</h3><div class="transitions"><button v-for="t in (supportsCatalog?SCENE_TRANSITIONS:SCENE_TRANSITIONS.slice(0,4))" :key="t.id" :aria-pressed="doc.transition===t.id" :class="{selected:doc.transition===t.id}" @click="doc.transition=t.id">{{ t.name }}</button></div>
  <VideoStudioEffectsLibrary v-if="supportsCatalog" v-model="doc"/>
  <template v-else><h3>Efeitos sonoros</h3><div v-for="field in ([{key:'transitionSound',name:'Som da transição'},{key:'accentSound',name:'Som do destaque'}] as const)" :key="field.key"><label>{{ field.name }}<select :value="motion[field.key]" @change="setSound(field.key,$event)"><option v-for="sound in SOUND_EFFECTS" :key="sound.id" :value="sound.id">{{ sound.name }}</option></select></label><audio controls preload="none" :src="'/video-studio/audio/'+soundAsset(motion[field.key])"/></div></template>
  <details><summary>Brilhos, partículas e intensidade</summary><div class="effects"><label v-for="effect in VIDEO_EFFECTS" :key="effect.id"><input v-model="doc.effects" type="checkbox" :value="effect.id"/>{{ effect.name }}</label></div><label>Intensidade<select v-model.number="doc.intensity"><option :value=".25">Suave</option><option :value=".55">Equilibrada</option><option :value=".85">Impactante</option></select></label></details>
  <button class="reset" @click="restore">Restaurar fundo, cores, música e efeitos do modelo</button>
 </section>
</template>
<style scoped>
.personalize{color:#263959}.personalize h3{font-size:18px;font-weight:700;margin:26px 0 8px}.personalize p,.personalize small{color:#64748b;font-size:13px;line-height:1.6}.backgrounds{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px;margin:16px 0}.backgrounds button{overflow:hidden;padding:6px 6px 10px;display:grid;gap:8px;font-size:12px}.backgrounds img,.original{width:100%;height:78px;object-fit:cover;border-radius:7px}.original{display:grid;place-items:center;background:#eeedf7;color:#5f5aa7;font-size:30px}.personalize button{border:1px solid #dce1eb;border-radius:10px;background:white;color:inherit;cursor:pointer;transition:border-color .15s,background .15s}.personalize button:hover{border-color:#9285d0}.personalize button.selected{border-color:#6556aa;box-shadow:0 0 0 1px #6556aa;background:#f0edf8}.palettes,.transitions{display:flex;flex-wrap:wrap;gap:8px;margin:15px 0}.palettes button,.transitions button{padding:10px 13px;font-size:12px;display:flex;gap:7px;align-items:center}.palettes i{height:17px;width:17px;border:2px solid;border-radius:50%}.personalize details{border-top:1px solid #e0e4ed;margin-top:20px;padding-top:15px;font-size:13px}.personalize summary{cursor:pointer;font-weight:600}.personalize label{display:flex;align-items:center;justify-content:space-between;gap:12px;font-size:13px;margin:14px 0}.personalize select,.campaign input{border:1px solid #dce1eb;border-radius:8px;padding:10px;background:white}.personalize .campaign{display:grid;gap:8px;margin-top:24px;font-weight:600}.effects{display:grid;grid-template-columns:1fr 1fr;gap:5px}.effects label{justify-content:flex-start;margin:8px 0}.personalize input[type=checkbox]{accent-color:#6556aa}.personalize .reset{padding:11px 14px;margin-top:20px;font-size:12px;color:#6556aa}.personalize button:focus-visible{outline:3px solid #9285d0;outline-offset:3px}
@media(max-width:480px){.backgrounds{grid-template-columns:1fr 1fr}}
.color-controls{display:flex;align-items:center;gap:8px}.color-controls input{width:36px;height:30px;cursor:pointer}.color-controls button{width:28px;height:28px}
</style>
