import test from 'node:test';
import assert from 'node:assert/strict';
import { compactProductSpace, bounds, piecewise } from './compact-product-space-lib.mjs';
const sample = () => ({ objects: [{ type: 'Rect', isFrame: true, _customId: 'frame', left: 0, top: 0, width: 1080, height: 1920 }, { type: 'Image', name: 'campaign-background', _customId: 'bg', src: '/same.png', width: 1080, height: 1920, left: 0, top: 0 }, { type: 'Rect', name: 'standard-validity-background', left: 100, top: 605, width: 900, height: 61.25 }, { type: 'Group', isProductZone: true, _customId: 'zone', originX: 'center', originY: 'center', left: 540, top: 1200, width: 1000, height: 900, objects: [{ type: 'Rect', width: 1000, height: 900 }], _zoneStateSnapshot: { zone: { geometry: {} }, cards: [] }, _zoneGlobalStyles: { gap: 12 } }, { type: 'Rect', name: 'footer-premium-background', left: 0, top: 1770, width: 1080, height: 130 }, { type: 'Textbox', businessProfileField: 'address', name: 'footer-address', left: 400, top: 1800, width: 300, height: 40, text: 'Address' }, { type: 'Image', name: 'campaign-seal', left: 10, top: 10, width: 500, height: 500 }] });
test('compacta validade e ganha área sem mover cabeçalho ou rodapé', () => { const c = sample(), r = compactProductSpace(c, { width: 1080, height: 1920 }); assert.ok(r.changes.length); const z = r.canvas.objects.find(o => o.isProductZone); assert.ok(bounds(z).height > 900); assert.equal(bounds(z).bottom, 1746); assert.deepEqual(r.canvas.objects.find(o => o.name === 'footer-address'), c.objects[5]); assert.deepEqual(r.canvas.objects.find(o => o.name === 'campaign-seal'), c.objects[6]); assert.equal(z._zoneHeight, bounds(z).height); assert.equal(z.objects[0].height, z.height); assert.equal(z._zoneStateSnapshot.zone.geometry.height, z.height); assert.equal(c.objects[3].height, 900); const slices = r.canvas.objects.filter(o => o.src); assert.equal(slices.reduce((n, o) => n + o.height, 0), 1920); for (let i = 1; i < slices.length; i++)
    assert.ok(Math.abs(bounds(slices[i - 1]).bottom - bounds(slices[i]).top) < 1e-6); assert.ok(slices.every(o => o.src === '/same.png')); });
test('não toca zona preenchida nem interpreta primeira zona como envelope de várias', () => { let c = sample(); c.objects[3]._zoneStateSnapshot.cards = [{ id: 'card' }]; assert.equal(compactProductSpace(c, { width: 1080, height: 1920 }).changes.length, 0); c = sample(); c.objects.push(structuredClone(c.objects[3])); assert.match(compactProductSpace(c, { width: 1080, height: 1920 }).reason, /múltiplas/); });
test('mapa é contínuo e mantém rodapé fixo', () => { const f = piecewise([[0, 0], [600, 600], [740, 676], [1700, 1746], [1770, 1770], [1920, 1920]]); assert.equal(f(600), 600); assert.equal(f(740), 676); assert.equal(f(1770), 1770); for (let y = 1; y <= 1920; y++)
    assert.ok(f(y) >= f(y - 1)); });
