import {videoValidityText} from './validity'
import {SocialIcon} from './showcase'
import {productLayers} from './product-layout'
import {CatalogTransition} from './catalog-effects'
import {VideoBackgroundImage} from './background-image'
import React,{createElement as h} from 'react'
import {AbsoluteFill,Audio,Img,Sequence,useCurrentFrame,useVideoConfig,interpolate} from 'remotion'
import {displayPrice,type VideoRenderProps,type VideoScene} from './model'
import {VideoPriceLabel} from './label-renderer'
const clamp=(n:number)=>Math.max(0,Math.min(1,n))
const out=(n:number)=>1-Math.pow(1-clamp(n),4)
const rnd=(i:number)=>{const n=Math.sin(i*93.173+73.21)*49271.65;return n-Math.floor(n)}
const div=(style:React.CSSProperties,...c:React.ReactNode[])=>h('div',{style},...c)
const abs=(x:number,y:number,w:number,hg:number,extra:React.CSSProperties={})=>({position:'absolute' as const,left:x,top:y,width:w,height:hg,...extra})
const condensed={fontFamily:'VideoCondensed, sans-serif',fontWeight:900,lineHeight:.95,textTransform:'uppercase' as const}
const text=(value:string,x:number,y:number,w:number,size:number,extra:React.CSSProperties={})=>div({...abs(x,y,w,undefined as any),...condensed,fontSize:size,color:'var(--video-text-color, white)',textAlign:'center',textShadow:'0 4px 5px #000c',...extra},value)
const fit=(s:string,size:number,limit:number)=>Math.max(size*.60,size*Math.min(1,Math.sqrt(limit/Math.max(1,s.length))))
const metalPath=(w:number,hg:number,c=65)=>`M${c} 0H${w-c}L${w} ${c}V${hg-c}L${w-c} ${hg}H${c}L0 ${hg-c}V${c}Z`
export const BROADCAST_CUES={frame:0,product:4,price:10,settled:18,exit:6}
function BevelFrame({width:w,height:hg}:{width:number;height:number}){
 return h('svg',{viewBox:`-20 -20 ${w+40} ${hg+40}`,style:{width:'100%',height:'100%',overflow:'visible'}},
 h('defs',null,h('linearGradient',{id:'metal',x1:0,y1:0,x2:1,y2:1},h('stop',{offset:0,stopColor:'#ff8165'}),h('stop',{offset:.2,stopColor:'#a52320'}),h('stop',{offset:.5,stopColor:'#2c090b'}),h('stop',{offset:.8,stopColor:'#f02f26'}),h('stop',{offset:1,stopColor:'#641013'})),h('pattern',{id:'carbon',width:12,height:12,patternUnits:'userSpaceOnUse'},h('rect',{width:12,height:12,fill:'#151313'}),h('path',{d:'M0 0L12 12M-6 6L6 18M6 -6L18 6',stroke:'#292424',strokeWidth:3}))),
 h('path',{d:metalPath(w,hg),fill:'#080707',stroke:'#070707',strokeWidth:32}),h('path',{d:metalPath(w,hg),fill:'url(#carbon)',stroke:'url(#metal)',strokeWidth:20}),h('path',{d:metalPath(w,hg),fill:'none',stroke:'#ff9a66',strokeWidth:2}),h('path',{d:metalPath(w-35,hg-35,50),transform:'translate(17.5 17.5)',fill:'none',stroke:'#4d4642',strokeWidth:4}),h('path',{d:metalPath(w-53,hg-53,45),transform:'translate(26.5 26.5)',fill:'none',stroke:'#070707',strokeWidth:7}),...[40,hg-40].flatMap(y=>[40,w-40].map(x=>h('g',{key:x+':'+y},h('circle',{cx:x,cy:y,r:8,fill:'#aaa19b',stroke:'#131313',strokeWidth:3}),h('path',{d:`M${x-4} ${y}H${x+4}`,stroke:'#1a1515',strokeWidth:2})))) )
}
function Atmosphere({props}:{props:VideoRenderProps}){
 const f=useCurrentFrame(),{width:w,height:hg}=useVideoConfig(),d=props.document,portrait=hg>w,seed=portrait?1:91
 const impact=Math.max(0,...props.scenes.map(s=>1-Math.abs(f-s.from-10)/5)),shake=d.effects.includes('shake')?Math.sin(f*2.8)*impact*9*d.intensity:0
 const elements:React.ReactNode[]=[]
 elements.push(h('svg',{key:'field',viewBox:`0 0 ${w} ${hg}`,style:{position:'absolute',inset:0,width:'100%',height:'100%'}},h('defs',null,h('pattern',{id:'hex',width:72,height:62,patternUnits:'userSpaceOnUse',patternTransform:`translate(${f*2%72} ${f*5%62}) rotate(-13)`},h('path',{d:'M18 0H54L72 31 54 62H18L0 31Z',fill:'none',stroke:'#8a4026',strokeWidth:2})),h('radialGradient',{id:'dark'},h('stop',{offset:0,stopColor:'#030303',stopOpacity:.96}),h('stop',{offset:.65,stopColor:'#0d0303',stopOpacity:.88}),h('stop',{offset:1,stopColor:'#6b2607',stopOpacity:.3}))),h('rect',{width:w,height:hg,fill:'#180703'}),h('rect',{width:w,height:hg,fill:'url(#hex)',opacity:.22}),h('rect',{width:w,height:hg,fill:'url(#dark)'})))
 elements.push(h(VideoBackgroundImage,{props}))
 if(d.effects.includes('rays')||d.effects.includes('glow'))for(let i=0;i<5;i++)elements.push(div({...abs(((f*24+i*w/3)%(w*2))-w,-hg*.3,80,hg*1.6),background:'linear-gradient(90deg,transparent,#ff9a2e50,transparent)',transform:'rotate(30deg)',opacity:.4}))
 if(d.effects.includes('embers')||d.effects.includes('fire'))for(let i=0;i<105;i++){const near=i%9===0,speed=near?22:7+rnd(i+4)*12,y=hg-((f*speed+rnd(i+seed)*hg)%(hg+200));elements.push(div({...abs(rnd(i+72)*w+Math.sin(f*.08+i)*18,y,near?7:2+rnd(i+6)*3,near?50:8+rnd(i+8)*15),background:'linear-gradient(#ffffc4,#ff7b16,transparent)',borderRadius:5,transform:'rotate(24deg)',opacity:(.18+rnd(i+11)*.8)*d.intensity,filter:near?'blur(1px)':undefined}))}
 if(d.effects.includes('fire')||d.effects.includes('smoke'))for(let i=0;i<3;i++)elements.push(div({...abs(i===1?w*.64:-w*.40,hg*(i===2?.65:.32)+Math.sin(f*.07+i)*45,w*.8,hg*.5),mixBlendMode:'screen',opacity:i===2?.28:.50,maskImage:'radial-gradient(ellipse,#000 20%,transparent 69%)',WebkitMaskImage:'radial-gradient(ellipse,#000 20%,transparent 69%)',transform:`translateX(${Math.sin(f*.11+i)*38}px) scale(${1.15+Math.sin(f*.15+i)*.08}) rotate(${i===1?-90:90}deg)`,filter:`url(#flame-warp)`},h(Img,{src:(props.templateBase||'/video-studio/templates')+'/impact-fire-v2.png',style:{width:'100%',height:'100%',objectFit:'cover'}})))
 elements.push(h('svg',{key:'filters',width:0,height:0},h('defs',null,h('filter',{id:'flame-warp',x:'-15%',y:'-15%',width:'130%',height:'130%'},h('feTurbulence',{type:'fractalNoise',baseFrequency:`${.012+Math.sin(f*.05)*.002} .025`,numOctaves:2,seed:9,result:'noise'}),h('feDisplacementMap',{in:'SourceGraphic',in2:'noise',scale:35+Math.sin(f*.12)*18,xChannelSelector:'R',yChannelSelector:'G'})))))
 for(const y of [-28,hg-28])elements.push(div({...abs(-100,y,w+200,55),background:'repeating-linear-gradient(115deg,#ffe93a 0px 28px,#956715 30px 34px,#191208 35px 63px)',transform:`translateX(${f*7%64}px) rotate(${y<0?-4:4}deg)`,opacity:.75,boxShadow:'0 0 24px #ff8c2750'}))
 return h(AbsoluteFill,{style:{overflow:'hidden',transform:`translateX(${shake}px) scale(1.02)`}},...elements)
}
function Badge({props,width,height}:{props:VideoRenderProps;width:number;height:number}){const d=props.document;if(d.campaign.trim().toUpperCase()==='FECHA MÊS')return h(Img,{src:(props.templateBase||'/video-studio/templates')+'/fecha-mes-badge-v1.png',style:{width,height,objectFit:'contain',filter:'drop-shadow(0 12px 6px #000b)'}});return div({...condensed,fontSize:fit(d.campaign,height*.45,16),color:'#ffe432',textShadow:'0 5px #9c4e0d,0 9px #592707,0 14px 12px #000',textAlign:'center'},d.campaign)}
function Logo({props,width,height}:{props:VideoRenderProps;width:number;height:number}){const logo=props.media[props.document.brand.logo];return logo?div({display:'flex',alignItems:'center',justifyContent:'center',width,height,padding:10,borderRadius:18,background:'#fff',boxShadow:'0 6px 18px #0008'},h(Img,{src:logo,style:{maxWidth:'100%',maxHeight:'100%',objectFit:'contain'}})):null}
function Header({props}:{props:VideoRenderProps}){const {width:w,height:hg}=useVideoConfig(),p=hg>w,d=props.document,b=d.brand;return p?div(abs(35,55,1010,415),div(abs(0,0,505,290),h(Badge,{props,width:505,height:290})),null,text(b.name,525,150,475,fit(b.name,65,25),{color:'#ffe629'}),null,div({...abs(0,362,1010,52),background:'#b61315',border:'2px solid #ff5e29',borderRadius:30,display:'flex',alignItems:'center',justifyContent:'center',padding:'0 25px',fontSize:fit(b.address,25,90),fontWeight:800,color:'var(--video-text-color, #fff)'} ,b.address||b.slogan||'CONFIRA AS OFERTAS')):
 div(abs(65,42,1790,175),div(abs(0,-10,350,190),h(Badge,{props,width:350,height:190})),null,text(b.name,645,8,1070,fit(b.name,70,36),{textAlign:'left',color:'#ffe629'}),null)}
function Price({props,price,unit}:{props:VideoRenderProps;price:string;unit:string}){const [integer,cents]=displayPrice(price).split(',');if(props.label)return h(VideoPriceLabel,{label:props.label,price,unit,colors:props.document.appearance});return div({display:'flex',alignItems:'stretch',height:'100%',filter:'drop-shadow(0 13px 4px #0009)',transform:'rotate(-3deg)'},div({width:'22%',background:'#090707',color:'var(--video-currency-color, var(--video-text-color, #fff))',display:'flex',alignItems:'center',justifyContent:'center',fontSize:66,...condensed,borderRadius:'20px 0 0 20px'},'R$'),div({width:'78%',background:'#fff02b',borderRadius:'0 20px 20px 0',color:'var(--video-price-color, #100708)',display:'flex',alignItems:'center',justifyContent:'center',gap:8,padding:'12px 25px'},div({...condensed,fontSize:Math.min(240,500/Math.max(2,integer!.length)),lineHeight:.87},integer),div({display:'flex',flexDirection:'column',alignSelf:'center'},div({...condensed,fontSize:118},','+cents),div({...condensed,fontSize:44,color:'var(--video-unit-color, #100708)',textAlign:'right',marginTop:12},unit||'UN'))))}
function Content({scene,props}:{scene:VideoScene;props:VideoRenderProps}){
 const f=useCurrentFrame(),{width:w,height:hg}=useVideoConfig(),p=hg>w,d=props.document,b=d.brand,offer=d.offers.find(o=>o.id===scene.id),intro=scene.id==='intro',outro=scene.id==='outro'
 const exit=clamp((f-(scene.frames-6))/6),stagger=(delay:number)=>out((f-delay)/7),pIn=stagger(4),priceIn=stagger(10),slam=(delay:number)=>{const n=f-delay;return n<0?.1:n<7?.1+1.02*out(n/7):1+.12*Math.exp(-(n-7)/3)*Math.cos((n-7)*.9)}
 const entrance=(delay:number,side=1)=>({opacity:clamp((f-delay)/2),transform:`translateX(${(1-stagger(delay))*w*.45*side-exit*w*.8}px) scale(${1-exit*.15})`,filter:f-delay<5?`blur(${Math.max(0,5-(f-delay))}px)`:undefined})
 if(intro)return h(AbsoluteFill,{style:{color:'var(--video-text-color, white)',transform:`scale(${1+exit*.25})`,opacity:1-exit}},div({...abs(p?300:765,p?125:55,p?480:390,p?200:125),...entrance(0)},h(Logo,{props,width:p?480:390,height:p?200:125})),text(b.name,p?70:260,p?360:200,p?940:1400,fit(b.name,p?89:85,30),{color:'var(--video-text-color, #fff)'}),div({...abs(p?20:390,p?530:290,p?1040:1140,p?630:560),transform:`scale(${slam(2)}) rotate(${(1-stagger(2))*-12}deg)`},h(Badge,{props,width:p?1040:1140,height:p?630:560})),text('OFERTAS QUE VOCÊ NÃO PODE PERDER',p?120:500,p?1280:820,p?840:920,p?92:67,{...entrance(8),color:'#ffeb30'}),text('CONFIRA AGORA',p?230:640,p?1570:950,p?620:640,p?49:38,{letterSpacing:5,...entrance(12)}))
 if(outro){const contactLines=[...new Set([b.address,...(b.addresses||[])].filter(Boolean)),...Array.from(new Set([b.whatsapp,...(b.whatsappNumbers||[])].filter(Boolean))).map(n=>'WhatsApp '+n),b.phone?'Telefone '+b.phone:'',b.instagram,b.facebook,b.website,b.hours?'Horário: '+b.hours:'',b.paymentNotes].filter((line):line is string=>Boolean(line));const top=p?1130:515,available=p?640:455;const lineCounts=contactLines.map(line=>Math.max(1,Math.ceil(line.length/(p?45:66))));const rowSize=Math.min(p?44:32,available/(lineCounts.reduce((a,b)=>a+b,0)*1.2+contactLines.length*.65));const rowTops=contactLines.map((_,i)=>top+lineCounts.slice(0,i).reduce((n,c)=>n+c*rowSize*1.2+rowSize*.65,0));return h(AbsoluteFill,{style:{color:'var(--video-text-color, white)'}},div({...abs(p?355:140,p?110:220,p?370:480,p?190:220),transform:`scale(${slam(0)})`},h(Logo,{props,width:p?370:480,height:p?190:220})),div({...abs(p?190:100,p?335:490,p?700:560,p?370:340),transform:`scale(${slam(3)})`},h(Badge,{props,width:p?700:560,height:p?370:340})),text(b.name,p?70:690,p?740:150,p?940:1120,fit(b.name,p?102:92,30),{color:'#ffe629',...entrance(6)}),text(b.slogan||'ESPERAMOS POR VOCÊ!',p?80:710,p?1000:345,p?920:1070,p?55:53,{...entrance(8)}),...contactLines.map((line,i)=>text(line,p?80:730,rowTops[i]!,p?920:1080,fit(line,rowSize,p?52:70),{fontFamily:'VideoBarlow',lineHeight:1.15,textTransform:'none',...entrance(10+i*2)})))}
 if(!offer)return null
 const panel={x:p?60:80,y:p?645:240,w:p?960:940,h:p?930:560}
 const validity=videoValidityText(d)
 return h(AbsoluteFill,null,div(abs(p?180:170,p?1635:850,p?720:700,p?130:100),h(Logo,{props,width:p?720:700,height:p?130:100})),validity?div({...abs(p?70:100,p?1790:980,p?940:850,p?60:40),display:'flex',alignItems:'center',justifyContent:'center',gap:10,fontSize:28,color:'var(--video-validity-color, var(--video-text-color, white))'},h(SocialIcon,{kind:'calendar',size:28}),validity):null,div({...abs(panel.x,panel.y,panel.w,panel.h),...entrance(0)},h(BevelFrame,{width:panel.w,height:panel.h})),
  text(offer.name,p?65:115,p?490:230,p?950:850,fit(offer.name,p?88:66,p?47:42),{...entrance(1,-1),lineHeight:1.02,color:'var(--video-name-color, var(--video-text-color, white))'}),
  div({...abs(p?95:115,p?730:355,p?890:850,p?740:430),opacity:clamp((f-4)/2),transform:`translate(${(1-pIn)*(p?650:-850)-exit*w}px,${(1-pIn)*120}px) scale(${slam(4)}) rotate(${(1-pIn)*14+Math.sin(f*.08)*.6}deg)`,filter:`drop-shadow(0 22px 14px #000b)${f<10?' blur('+Math.max(0,10-f)+'px)':''}`},...productLayers([0,0,p?890:850,p?740:500],p,d.duplicateProducts!==false,offer.imageAspectRatio||1,offer.copies).map(layer=>h('div',{key:layer.motionIndex,style:{...abs(...layer.box),rotate:`${layer.rotation}deg`}},props.media[offer.image]?h(Img,{src:props.media[offer.image]!,style:{width:'100%',height:'100%',objectFit:'contain'}}):text('ADICIONE A FOTO',0,180,800,60)))),
  div({...abs(p?305:1055,p?1270:590,p?685:710,p?280:310),opacity:clamp((f-10)/2),transform:`translateY(${(1-priceIn)*220+exit*400}px) scale(${slam(10)})`},h(Price,{props,price:offer.price,unit:offer.unit})),
  text([props.label?offer.unit:'',offer.condition].filter(Boolean).join(' • '),p?90:1050,p?1560:930,p?900:760,fit(offer.condition,p?35:31,75),{color:'var(--video-condition-color, var(--video-text-color, #fff))',...entrance(13)}))
}
export function BroadcastComposition(props:VideoRenderProps){const f=useCurrentFrame(),d=props.document,{durationInFrames}=useVideoConfig(),current=props.scenes.find(s=>f>=s.from&&f<s.from+s.frames),products=current&&current.id!=='intro'&&current.id!=='outro';const fonts=props.fontBase||'/art-studio/fonts';const transition=props.scenes.find(s=>f>=s.from&&f<s.from+6&&s.from>0);const tf=transition?f-transition.from:99;return h(AbsoluteFill,{style:{background:'#080303',fontFamily:'VideoBarlow',overflow:'hidden'}},h('style',null,`@font-face{font-family:VideoBarlow;src:url('${fonts}/Barlow-ExtraBold.ttf')}@font-face{font-family:VideoCondensed;src:url('${fonts}/BarlowCondensed-ExtraBold.ttf')}`),h(Atmosphere,{props}),products?h(Header,{props}):null,...props.scenes.map(s=>h(Sequence,{key:s.id,from:s.from,durationInFrames:s.frames},h(Content,{props,scene:s}),s.audio&&d.voice.enabled?h(Audio,{src:s.audio,playbackRate:s.playbackRate||1,volume:d.audio.voiceVolume}):null,d.audio.sounds&&props.whoosh?h(Audio,{src:props.whoosh,volume:d.audio.effectsVolume*.8}):null,d.audio.sounds&&props.impact?h(Sequence,{from:10},h(Audio,{src:props.impact,volume:d.audio.effectsVolume})):null)),h(CatalogTransition,{props}),props.music&&d.audio.music!=='none'?h(Audio,{src:props.music,loop:true,volume:(frame:number)=>{const speech=props.scenes.find(s=>(s.audio||props.voiceAudio)&&frame>=s.from-5&&frame<s.from+(s.speechFrames||s.frames)+10);return d.audio.musicVolume*(speech?.28:1)*Math.min(1,frame/5,(durationInFrames-frame)/8)}}):null)}
